#!/usr/bin/env sh
set -e

# Common constants
COLOR_RESET='\033[0m'
COLOR_GREEN='\033[0;32m'
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-${PWD##*/}}"
TEST_HOST="${TEST_HOST:-localhost}"

echo "Integration test host: ${TEST_HOST}"

get_exposed_port() {
  if [ -z $3 ]
  then
    docker-compose port $1 $2 | cut -d: -f2
  else
    docker-compose port --index=$3 $1 $2 | cut -d: -f2
  fi
}

report_start() {
  printf "Waiting for $1 ... "
}

report_done() {
  printf "${COLOR_GREEN}done${COLOR_RESET}\n"
}

wait_for_healthy_containers() {
  IDs=$(docker-compose ps -q | paste -sd " " -)
  report_start "${1} containers to report healthy"
  counter="0"
  while true
  do
    if [ "$(docker inspect -f "{{.State.Health.Status}}" ${IDs} | grep -c healthy)" -eq "${1}" ]; then
      break
    fi
    counter=$((++counter))
    if [ "${counter}" -eq 120 ]; then
      echo " ERROR: containers failed to start"
      exit 1
    fi
    sleep 1
  done
  report_done
}

# Ensure Docker is Running
echo "Docker Information:"
echo ""
docker version
echo ""

# Activate the virtual environment
if test -e env/bin/activate
then
  . ./env/bin/activate
fi

rm -rf build
mkdir -p build build/data

# Stop any running instances and clean up after them, then pull images
docker-compose down --volumes --remove-orphans
docker-compose up -d --quiet-pull

wait_for_healthy_containers 1

docker-compose exec postgres /usr/bin/pgbench -i -U postgres postgres

printf "Creating test backups ... "
docker-compose exec postgres /usr/bin/pg_dump -Fc -U postgres -f /data/dump.custom -d postgres
docker-compose exec postgres /usr/bin/pg_dump -Fd -U postgres -f /data/dump.directory -d postgres
docker-compose exec postgres /usr/bin/pg_dump -Ft -U postgres -f /data/dump.tar -d postgres
report_done

docker-compose exec postgres ls -al /data
ls -al build/data

cat > build/test-environment<<EOF
export PGHOST=${TEST_HOST}
export PGPORT=$(get_exposed_port postgres 5432)
export PGDATABASE=postgres
export PGUSER=postgres
EOF

printf "\nBootstrap complete\n\nDon't forget to \". build/test-environment\"\n"
