services:
  postgres:
    image: postgres:17
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432
    volumes:
      - type: bind
        source: ./build/data
        target: /data
      - type: bind
        source: ./fixtures
        target: /fixtures
